### PR TITLE
Cache the CID

### PR DESCRIPTION
**Pull request by Stebalien**
Computing it is expensive.

### CODE REVIEW

**Comment by Kubuxu** [comment]
There is similar code in go-ipfs (I think with blocks) because they get reused I think it might need similar treatment.

**Comment by Stebalien** [comment]
Ah, I assumed this could only be written from one thread. Technically, assuming data can't change, this is a safe race (at worst, the work will be repeated once per thread) but that runs afoul of go's "don't be clever" rule.

Another solution would be to just pre-compute it as do `RawNode` and `BasicBlock` as CBOR nodes are *currently* immutable.

> There is similar code in go-ipfs (I think with blocks) because they get reused I think it might need similar treatment. 

I assume you mean `ProtoNode`? Currently, it's editable so using `Once` will be a bit trickier. However, one is only *supposed* to edit it after copying it so we could just not copy the data and the cid and then disallow edits once they've been initialized.

Personally, I'd rather go with:

```go
var editable EditableNode := my_node_of_any_type.Edit()
// Make edits....
var new_node Node := editable.Commit()
```

but @whyrusleeping said that there were problems with this (too complicated?).

However, I'd like to point out that, if we fix this problem and use `Once`, calling `Copy` will be equivalent to `Edit` and calling `Cid` or `RawData` will be equivalent to calling some `Commit` method.

> `sync.Once` will also have lower overhead as it uses atomic read for fastpath instead of always locking for read.

Than mutexes but bare pointer reads will still be slightly faster (except where one ends up doing all the work twice due to a race).

**Comment by Kubuxu** [comment]
I am thinking about a case on on read race.

1. Create instance of cbor-ipld node.
2. Share it with someone
3. You both call `node.Cid()`
4. ...
5. Race happened, you both should converge to the same value but it is still data race.

Yes this structure should be seen as read-only, at least IMO.

**Comment by Kubuxu** [comment]
This structure is read only and all methods on it are accepting the copy of the structure (not a pointer). This means that your caching code doesn't work as you are storing the cached cid in local copy of the structure.

**Comment by Stebalien** [comment]
> This structure is read only and all methods on it are accepting the copy of the structure (not a pointer) but your caching code still won't work and if it worked there would be race on updating the cid field.

Ah, good point. However, not *all* methods accept a copy (e.g, `Tree`). On that topic, why do they do that? `ProtoNode`s don't.

> if it worked there would be race on updating the cid field

As I said above, this would be a *harmless* race but I agree that it should be "fixed" under the don't be clever rule.

**Comment by Kubuxu** [comment]
I agree it would be *harmless* but race nevertheless, it might behave badly in case of architectures with 32 bit registers and 64 bit pointers (I am not sure if any like that exist) but then the 64 bit write is not atomic which could lead to inconsistent address being written (two writes overriding one another).

Will you try this patch again?

**Comment by Kubuxu** [comment]
No idea why, I think it isn't  needed in  most cases. Do you want to try cleaning it up?

**Comment by Stebalien** [comment]
> Will you try this patch again?

> No idea why, I think it isn't needed in most cases. Do you want to try cleaning it up?

#13

> Will you try this patch again?

I'd like @whyrusleeping's opinion first.  He indicated that `ProtoBuf`, at least, doesn't need to be thread safe (never shared by pointer between threads).

**Comment by Kubuxu** [comment]
The problem I see here is that the structure looks threadsafe (just simple getters, but with lazy cashing it no longer is).

**Comment by Stebalien** [comment]
I agree. I've submitted an issue for fixing `ProtoNode` [here](https://github.com/ipfs/go-ipfs/issues/3991).

**Comment by Stebalien** [comment]
However, given that `cbornode.Node` is immutable, it might make more sense to just pre-compute the CID up-front instead of doing so lazily (we're already serializing up-front).

**Pull request closed without merging**
